import uuid
from enum import Enum
from typing import Optional, List
from pydantic import BaseModel, Field
from app.schemas.facility import FacilityAvailability

class UrgencyLevel(str, Enum):
    EMERGENCY = "EMERGENCY"
    URGENT = "URGENT"
    ROUTINE = "ROUTINE"
    SELF_CARE = "SELF_CARE"

class SymptomInput(BaseModel):
    symptoms: str
    language: str = "en"
    channel: str = "WEB"
    patient_id: Optional[uuid.UUID] = None
    telegram_chat_id: Optional[int] = None
    latitude: Optional[float] = None
    longitude: Optional[float] = None

class TriageAssessment(BaseModel):
    urgency_level: UrgencyLevel
    primary_symptoms: List[str] = Field(default_factory=list)
    red_flags_present: bool = False
    potential_categories: List[str] = Field(default_factory=lambda: ["General"])
    recommended_specialty: str = "General Medicine"
    advisory_summary: str
    next_steps: List[str] = Field(default_factory=list)
    home_remedies: List[str] = Field(default_factory=list, description="Specific, safe home care remedies (gargling, steam, hydration) for mild conditions")
    is_severe: bool = Field(default=False, description="True if condition is EMERGENCY or URGENT, requiring hospital ticket")
    mandatory_disclaimer: str = "DISCLAIMER: This assessment is generated by an AI assistant for informational and triage routing purposes only. It is NOT a medical diagnosis. Please confirm with a qualified healthcare professional."

class TriageResponse(BaseModel):
    session_id: uuid.UUID
    assessment: TriageAssessment
    facilities: List[FacilityAvailability]

